### ISSUE TITLE
Since 0.2.2 multi module Android project doesn't run

### ISSUE THREAD

**Issue by yschimke** [tylerbwong/metalava-gradle#39]
Working around with this PR https://github.com/google/horologist/pull/483

But updating from 0.1.9 to 0.2.3 caused metalava to silently skip running.  Moving the plugin configuration to the individual modules seems to fix it.

Our original config comes from https://github.com/google/accompanist/blob/main/build.gradle#L153-L160.

**Comment by tylerbwong** [comment]
Hey @yschimke, sorry for the late reply. I've since released version 0.3.1. Can you try it out and let me know if you're still seeing the issue? Thanks!

**Comment by yschimke** [comment]
No, still seems to have the same problem.

I tried various versions of it on here https://github.com/google/horologist/pull/654/files, but in the end it only appears to be activated on the JVM library project.  None of the Android libs.

Does it work on multi module projects with a mix?

**Comment by tylerbwong** [comment]
Hmmm, that's odd. The only thing I can think off that changed in 0.2.3 is that we added Android Variant support, so task names for Android modules are appended with a specific variant. Plain Java/Kotlin modules will not have the variant name attached to the task, so maybe it's possible some modules are missed because of an incorrect task name (`metalavaCheckCompatibility` vs. `metalavaCheckCompatibilityRelease`)?

**Comment by yschimke** [comment]
Yep, I guess I expected metalavaCheckCompatibility to run all, which is used to do.

Feel free to close if this is expected.
